# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwXWmCYIMiVRRLcHb4oAcfbH7ssWutNn
"""

import streamlit as st
import cv2
import face_recognition
import numpy as np
import pandas as pd
from datetime import datetime
import pickle
import os
from pathlib import Path
import io
from PIL import Image

# Page configuration
st.set_page_config(
    page_title="Face Recognition Attendance System",
    page_icon="📸",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Create necessary directories
Path("data").mkdir(exist_ok=True)
Path("data/employee_images").mkdir(exist_ok=True)

# File paths
EMPLOYEES_FILE = "data/employees.pkl"
ATTENDANCE_FILE = "data/attendance.csv"
ENCODINGS_FILE = "data/face_encodings.pkl"

# Initialize session state
if 'employees' not in st.session_state:
    st.session_state.employees = {}
if 'face_encodings' not in st.session_state:
    st.session_state.face_encodings = {}
if 'attendance_records' not in st.session_state:
    st.session_state.attendance_records = []

# Load data functions
def load_data():
    """Load employees and face encodings from files"""
    try:
        if os.path.exists(EMPLOYEES_FILE):
            with open(EMPLOYEES_FILE, 'rb') as f:
                st.session_state.employees = pickle.load(f)

        if os.path.exists(ENCODINGS_FILE):
            with open(ENCODINGS_FILE, 'rb') as f:
                st.session_state.face_encodings = pickle.load(f)

        if os.path.exists(ATTENDANCE_FILE):
            df = pd.read_csv(ATTENDANCE_FILE)
            st.session_state.attendance_records = df.to_dict('records')
    except Exception as e:
        st.error(f"Error loading data: {e}")

def save_data():
    """Save employees and face encodings to files"""
    try:
        with open(EMPLOYEES_FILE, 'wb') as f:
            pickle.dump(st.session_state.employees, f)

        with open(ENCODINGS_FILE, 'wb') as f:
            pickle.dump(st.session_state.face_encodings, f)

        if st.session_state.attendance_records:
            df = pd.DataFrame(st.session_state.attendance_records)
            df.to_csv(ATTENDANCE_FILE, index=False)
    except Exception as e:
        st.error(f"Error saving data: {e}")

def register_employee(name, employee_id, image):
    """Register a new employee with face encoding"""
    try:
        # Convert image to RGB
        rgb_image = cv2.cvtColor(np.array(image), cv2.COLOR_BGR2RGB)

        # Detect face and get encoding
        face_locations = face_recognition.face_locations(rgb_image)

        if len(face_locations) == 0:
            return False, "No face detected in the image. Please try again."

        if len(face_locations) > 1:
            return False, "Multiple faces detected. Please ensure only one person is in the image."

        face_encoding = face_recognition.face_encodings(rgb_image, face_locations)[0]

        # Save employee data
        st.session_state.employees[employee_id] = {
            'name': name,
            'employee_id': employee_id,
            'registered_date': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        st.session_state.face_encodings[employee_id] = face_encoding

        # Save image
        image_path = f"data/employee_images/{employee_id}.jpg"
        cv2.imwrite(image_path, cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR))

        save_data()
        return True, "Employee registered successfully!"

    except Exception as e:
        return False, f"Error during registration: {str(e)}"

def recognize_face(image):
    """Recognize face from image"""
    try:
        # Convert image to RGB
        rgb_image = cv2.cvtColor(np.array(image), cv2.COLOR_BGR2RGB)

        # Detect faces
        face_locations = face_recognition.face_locations(rgb_image)

        if len(face_locations) == 0:
            return None, "No face detected"

        face_encodings = face_recognition.face_encodings(rgb_image, face_locations)

        if len(face_encodings) == 0:
            return None, "Could not encode face"

        face_encoding = face_encodings[0]

        # Compare with known faces
        if not st.session_state.face_encodings:
            return None, "No registered employees"

        known_encodings = list(st.session_state.face_encodings.values())
        known_ids = list(st.session_state.face_encodings.keys())

        matches = face_recognition.compare_faces(known_encodings, face_encoding, tolerance=0.6)
        face_distances = face_recognition.face_distance(known_encodings, face_encoding)

        if True in matches:
            best_match_index = np.argmin(face_distances)
            if matches[best_match_index]:
                employee_id = known_ids[best_match_index]
                confidence = (1 - face_distances[best_match_index]) * 100
                return employee_id, f"Match found with {confidence:.2f}% confidence"

        return None, "No match found"

    except Exception as e:
        return None, f"Error: {str(e)}"

def mark_attendance(employee_id):
    """Mark attendance for an employee"""
    if employee_id not in st.session_state.employees:
        return False, "Employee not found"

    today = datetime.now().date()

    # Check if already marked today
    for record in st.session_state.attendance_records:
        if (record['employee_id'] == employee_id and
            datetime.strptime(record['date'], "%Y-%m-%d").date() == today):
            return False, "Attendance already marked today"

    # Add attendance record
    employee = st.session_state.employees[employee_id]
    record = {
        'employee_id': employee_id,
        'name': employee['name'],
        'date': datetime.now().strftime("%Y-%m-%d"),
        'time': datetime.now().strftime("%H:%M:%S"),
        'status': 'Present'
    }

    st.session_state.attendance_records.append(record)
    save_data()

    return True, f"Attendance marked for {employee['name']}"

# Main App
def main():
    load_data()

    # Title and header
    st.title("📸 Face Recognition Attendance System")
    st.markdown("---")

    # Sidebar
    with st.sidebar:
        st.header("Navigation")
        page = st.radio(
            "Select Page",
            ["📝 Register Employee", "✅ Mark Attendance", "📊 View Records", "👥 Manage Employees"]
        )

        st.markdown("---")
        st.metric("Total Employees", len(st.session_state.employees))
        st.metric("Total Records", len(st.session_state.attendance_records))

        # Today's attendance
        today = datetime.now().date()
        today_count = sum(1 for r in st.session_state.attendance_records
                         if datetime.strptime(r['date'], "%Y-%m-%d").date() == today)
        st.metric("Today's Attendance", today_count)

    # Register Employee Page
    if page == "📝 Register Employee":
        st.header("Register New Employee")

        col1, col2 = st.columns([1, 1])

        with col1:
            name = st.text_input("Employee Name", placeholder="Enter full name")
            employee_id = st.text_input("Employee ID", placeholder="Enter unique ID")

            # Image upload or camera
            upload_method = st.radio("Choose input method", ["Upload Image", "Use Camera"])

            if upload_method == "Upload Image":
                uploaded_file = st.file_uploader("Upload employee photo", type=['jpg', 'jpeg', 'png'])
                if uploaded_file:
                    image = Image.open(uploaded_file)
                    st.image(image, caption="Uploaded Image", use_column_width=True)

                    if st.button("Register Employee", type="primary"):
                        if name and employee_id:
                            success, message = register_employee(name, employee_id, image)
                            if success:
                                st.success(message)
                                st.balloons()
                            else:
                                st.error(message)
                        else:
                            st.warning("Please fill all fields")

            else:
                camera_image = st.camera_input("Take a photo")
                if camera_image:
                    image = Image.open(camera_image)

                    if st.button("Register Employee", type="primary"):
                        if name and employee_id:
                            success, message = register_employee(name, employee_id, image)
                            if success:
                                st.success(message)
                                st.balloons()
                            else:
                                st.error(message)
                        else:
                            st.warning("Please fill all fields")

        with col2:
            st.subheader("Registered Employees")
            if st.session_state.employees:
                for emp_id, emp_data in st.session_state.employees.items():
                    with st.expander(f"{emp_data['name']} ({emp_id})"):
                        st.write(f"**Employee ID:** {emp_id}")
                        st.write(f"**Name:** {emp_data['name']}")
                        st.write(f"**Registered:** {emp_data['registered_date']}")

                        image_path = f"data/employee_images/{emp_id}.jpg"
                        if os.path.exists(image_path):
                            st.image(image_path, width=150)
            else:
                st.info("No employees registered yet")

    # Mark Attendance Page
    elif page == "✅ Mark Attendance":
        st.header("Mark Attendance")

        col1, col2 = st.columns([1, 1])

        with col1:
            input_method = st.radio("Choose input method", ["Upload Image", "Use Camera"])

            if input_method == "Upload Image":
                uploaded_file = st.file_uploader("Upload photo for recognition", type=['jpg', 'jpeg', 'png'])
                if uploaded_file:
                    image = Image.open(uploaded_file)
                    st.image(image, caption="Uploaded Image", use_column_width=True)

                    if st.button("Recognize & Mark Attendance", type="primary"):
                        with st.spinner("Recognizing face..."):
                            employee_id, message = recognize_face(image)

                            if employee_id:
                                st.success(message)
                                success, att_message = mark_attendance(employee_id)
                                if success:
                                    st.success(att_message)
                                    st.balloons()
                                else:
                                    st.warning(att_message)
                            else:
                                st.error(message)

            else:
                camera_image = st.camera_input("Take a photo")
                if camera_image:
                    image = Image.open(camera_image)

                    if st.button("Recognize & Mark Attendance", type="primary"):
                        with st.spinner("Recognizing face..."):
                            employee_id, message = recognize_face(image)

                            if employee_id:
                                st.success(message)
                                success, att_message = mark_attendance(employee_id)
                                if success:
                                    st.success(att_message)
                                    st.balloons()
                                else:
                                    st.warning(att_message)
                            else:
                                st.error(message)

        with col2:
            st.subheader("Today's Attendance")
            today = datetime.now().date()
            today_records = [r for r in st.session_state.attendance_records
                           if datetime.strptime(r['date'], "%Y-%m-%d").date() == today]

            if today_records:
                df = pd.DataFrame(today_records)
                st.dataframe(df, use_container_width=True)
            else:
                st.info("No attendance marked today")

    # View Records Page
    elif page == "📊 View Records":
        st.header("Attendance Records")

        if st.session_state.attendance_records:
            df = pd.DataFrame(st.session_state.attendance_records)

            # Filters
            col1, col2, col3 = st.columns(3)

            with col1:
                date_filter = st.date_input("Filter by Date", value=None)

            with col2:
                if st.session_state.employees:
                    employee_names = ["All"] + [emp['name'] for emp in st.session_state.employees.values()]
                    name_filter = st.selectbox("Filter by Employee", employee_names)

            with col3:
                st.write("")
                st.write("")
                if st.button("Clear Filters"):
                    st.rerun()

            # Apply filters
            filtered_df = df.copy()

            if date_filter:
                filtered_df = filtered_df[
                    pd.to_datetime(filtered_df['date']).dt.date == date_filter
                ]

            if 'name_filter' in locals() and name_filter != "All":
                filtered_df = filtered_df[filtered_df['name'] == name_filter]

            # Display data
            st.dataframe(filtered_df, use_container_width=True)

            # Statistics
            st.subheader("Statistics")
            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric("Total Records", len(filtered_df))

            with col2:
                unique_employees = filtered_df['employee_id'].nunique()
                st.metric("Unique Employees", unique_employees)

            with col3:
                if not filtered_df.empty:
                    avg_daily = len(filtered_df) / filtered_df['date'].nunique()
                    st.metric("Avg Daily Attendance", f"{avg_daily:.1f}")

            # Download button
            csv = filtered_df.to_csv(index=False)
            st.download_button(
                label="📥 Download CSV",
                data=csv,
                file_name=f"attendance_{datetime.now().strftime('%Y%m%d')}.csv",
                mime="text/csv"
            )

        else:
            st.info("No attendance records available")

    # Manage Employees Page
    elif page == "👥 Manage Employees":
        st.header("Manage Employees")

        if st.session_state.employees:
            for emp_id, emp_data in st.session_state.employees.items():
                with st.expander(f"{emp_data['name']} ({emp_id})"):
                    col1, col2 = st.columns([2, 1])

                    with col1:
                        st.write(f"**Employee ID:** {emp_id}")
                        st.write(f"**Name:** {emp_data['name']}")
                        st.write(f"**Registered:** {emp_data['registered_date']}")

                        # Show attendance count
                        emp_records = [r for r in st.session_state.attendance_records
                                     if r['employee_id'] == emp_id]
                        st.write(f"**Total Attendance:** {len(emp_records)} days")

                    with col2:
                        image_path = f"data/employee_images/{emp_id}.jpg"
                        if os.path.exists(image_path):
                            st.image(image_path, width=150)

                    if st.button(f"Delete {emp_data['name']}", key=f"del_{emp_id}"):
                        # Delete employee
                        del st.session_state.employees[emp_id]
                        del st.session_state.face_encodings[emp_id]

                        # Delete image
                        if os.path.exists(image_path):
                            os.remove(image_path)

                        save_data()
                        st.success(f"Deleted {emp_data['name']}")
                        st.rerun()
        else:
            st.info("No employees registered yet")

        # Clear all data
        st.markdown("---")
        st.subheader("⚠️ Danger Zone")
        if st.button("Clear All Data", type="secondary"):
            if st.checkbox("I understand this will delete all data"):
                st.session_state.employees = {}
                st.session_state.face_encodings = {}
                st.session_state.attendance_records = []
                save_data()
                st.success("All data cleared")
                st.rerun()

if __name__ == "__main__":
    main()